### ISSUE TITLE
.env variables

### ISSUE THREAD

**Issue by MattLoyeD** [kwinyyyc/strapi-plugin-zeasy-image-api#21]
Hey :)

Would you mind integrating .env variables instead of a config.json ?

I don't really know how to do that.

Thanks !

**Comment by kwinyyyc** [comment]
@MattLoyeD since stable version (strapi 3.x.x), it does support `.env` variables.

In that case, there should be a `config/plugin.js` in your application, add below section to the file.
```js
module.exports = ({ env }) => {
  return {
    'zeasy-image-api': {
      providerOptions: {
        unsplash: {
          appName: env('UNSPLASH_APP_NAME'),
          accessKey: env('UNSPLASH_ACCESS_KEY'),
        },
        giphy: {
          accessKey: env('GIPHY_API_KEY'),
        },
      },
    },
  };
};
```

Then make sure you have below variables in your `.env` file
UNSPLASH_APP_NAME=XXXXXXX
UNSPLASH_ACCESS_KEY=XXXXXX
GIPHY_API_KEY=XXXXXX

**Comment by MattLoyeD** [comment]
Nice 👍 
You really should add this to the main documentation :).

Thanks again !

**Comment by kwinyyyc** [comment]
@MattLoyeD Typo there, the filename has to be `config/plugins.js` in plural form.
